{% set name = "amara3.iri" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amara3.iri-{{ version }}.tar.gz
  sha256: 442d693241d370ad03907d8d1a22aa2797228949cb4d28262c351526edd3f1be
  patches:
    - 0001-Remove-pytest-from-requirements.patch

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - amara3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uogbuji/amara3-iri
  summary: ('Module for handling Internationalized Resource Identifiers (IRIs). Core of the Amara3 project, which offers a variety of data processing tools.',)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
